// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddEntries(arg1:Array<main.Entry>):Promise<boolean>;

export function GetEntries(arg1:number,arg2:boolean):Promise<Array<main.Entry>>;

export function GetHashStats():Promise<main.HashStats>;

export function GetMeta():Promise<Array<any>>;

export function GetPassword(arg1:string):Promise<string>;

export function GetTotalEntries(arg1:boolean):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function StartHashing(arg1:Array<string>):Promise<void>;

export function UpdateStats(arg1:boolean):Promise<void>;
