// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntries(arg1) {
  return window['go']['main']['App']['AddEntries'](arg1);
}

export function GetEntries(arg1, arg2) {
  return window['go']['main']['App']['GetEntries'](arg1, arg2);
}

export function GetMeta() {
  return window['go']['main']['App']['GetMeta']();
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function GetTotalEntries(arg1) {
  return window['go']['main']['App']['GetTotalEntries'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartHashing(arg1) {
  return window['go']['main']['App']['StartHashing'](arg1);
}
